language: python
cache: pip
dist: bionic
python:
  - "2.7_with_system_site_packages"
  - "3.7"
addons:
  apt:
    packages:
      - build-essential
      - libcap-dev
      - python-qt4
      - python-pyqt5
      - tor
      - xvfb
install:
  - pip install -r requirements.txt
  - python setup.py install
  - export PYTHONWARNINGS=all
script:
  - python checkdeps.py
  - python src/bitmessagemain.py -t
  - python -bm tests
